import React from 'react';
import { TextArea } from '@/components/ui/TextArea';

export default function TextareaExample() {
  const [basicValue, setBasicValue] = React.useState('');
  const [helperValue, setHelperValue] = React.useState('');
  const [errorValue, setErrorValue] = React.useState('Invalid input text');
  const [counterValue, setCounterValue] = React.useState('');
  const [magicValue, setMagicValue] = React.useState('This content was generated by AI');
  const [smallValue, setSmallValue] = React.useState('');
  const [allFeaturesValue, setAllFeaturesValue] = React.useState('');

  return (
    <div style={{ padding: '32px', display: 'flex', flexDirection: 'column', gap: '48px', maxWidth: '800px' }}>
      <section>
        <h2 style={{
          fontSize: '24px',
          fontWeight: '700',
          fontFamily: 'var(--ld-semantic-font-family-sans)',
          color: 'var(--ld-semantic-color-text)',
          marginBottom: '24px'
        }}>
          TextArea Component Examples
        </h2>
        <p style={{
          fontSize: '14px',
          fontFamily: 'var(--ld-semantic-font-family-sans)',
          color: 'var(--ld-semantic-color-text-subtle)',
          marginBottom: '32px'
        }}>
          Living Design 3.5 TextArea component with support for various states, sizes, and features.
        </p>
      </section>

      <section>
        <h3 style={{
          fontSize: '18px',
          fontWeight: '700',
          fontFamily: 'var(--ld-semantic-font-family-sans)',
          color: 'var(--ld-semantic-color-text)',
          marginBottom: '16px'
        }}>
          Basic TextArea
        </h3>
        <TextArea
          label="Description"
          value={basicValue}
          onChange={(e) => setBasicValue(e.target.value)}
          textAreaProps={{ placeholder: 'Enter your description here...' }}
        />
      </section>

      <section>
        <h3 style={{
          fontSize: '18px',
          fontWeight: '700',
          fontFamily: 'var(--ld-semantic-font-family-sans)',
          color: 'var(--ld-semantic-color-text)',
          marginBottom: '16px'
        }}>
          With Helper Text
        </h3>
        <TextArea
          label="Comments"
          value={helperValue}
          onChange={(e) => setHelperValue(e.target.value)}
          helperText="Please provide detailed feedback"
          textAreaProps={{ placeholder: 'Type your comments...' }}
        />
      </section>

      <section>
        <h3 style={{
          fontSize: '18px',
          fontWeight: '700',
          fontFamily: 'var(--ld-semantic-font-family-sans)',
          color: 'var(--ld-semantic-color-text)',
          marginBottom: '16px'
        }}>
          Error State
        </h3>
        <TextArea
          label="User Input"
          value={errorValue}
          onChange={(e) => setErrorValue(e.target.value)}
          error="This field contains invalid content"
          textAreaProps={{ placeholder: 'Enter valid text...' }}
        />
      </section>

      <section>
        <h3 style={{
          fontSize: '18px',
          fontWeight: '700',
          fontFamily: 'var(--ld-semantic-font-family-sans)',
          color: 'var(--ld-semantic-color-text)',
          marginBottom: '16px'
        }}>
          With Character Counter
        </h3>
        <TextArea
          label="Bio"
          value={counterValue}
          onChange={(e) => setCounterValue(e.target.value)}
          maxLength={100}
          helperText="Tell us about yourself"
          textAreaProps={{ placeholder: 'Write a short bio...' }}
        />
      </section>

      <section>
        <h3 style={{
          fontSize: '18px',
          fontWeight: '700',
          fontFamily: 'var(--ld-semantic-font-family-sans)',
          color: 'var(--ld-semantic-color-text)',
          marginBottom: '16px'
        }}>
          Magic (AI Generated) Content
        </h3>
        <TextArea
          label="AI Response"
          value={magicValue}
          onChange={(e) => setMagicValue(e.target.value)}
          isMagic
          helperText="This content was generated by AI"
        />
      </section>

      <section>
        <h3 style={{
          fontSize: '18px',
          fontWeight: '700',
          fontFamily: 'var(--ld-semantic-font-family-sans)',
          color: 'var(--ld-semantic-color-text)',
          marginBottom: '16px'
        }}>
          Small Size
        </h3>
        <TextArea
          label="Quick Note"
          value={smallValue}
          onChange={(e) => setSmallValue(e.target.value)}
          size="small"
          helperText="For condensed layouts"
          textAreaProps={{ placeholder: 'Add a quick note...' }}
        />
      </section>

      <section>
        <h3 style={{
          fontSize: '18px',
          fontWeight: '700',
          fontFamily: 'var(--ld-semantic-font-family-sans)',
          color: 'var(--ld-semantic-color-text)',
          marginBottom: '16px'
        }}>
          Disabled State
        </h3>
        <TextArea
          label="Disabled Field"
          value="This field is disabled"
          disabled
          helperText="This field cannot be edited"
        />
      </section>

      <section>
        <h3 style={{
          fontSize: '18px',
          fontWeight: '700',
          fontFamily: 'var(--ld-semantic-font-family-sans)',
          color: 'var(--ld-semantic-color-text)',
          marginBottom: '16px'
        }}>
          Read-only State
        </h3>
        <TextArea
          label="Terms and Conditions"
          value="This content is read-only. You can select and copy the text but cannot modify it."
          readOnly
        />
      </section>

      <section>
        <h3 style={{
          fontSize: '18px',
          fontWeight: '700',
          fontFamily: 'var(--ld-semantic-font-family-sans)',
          color: 'var(--ld-semantic-color-text)',
          marginBottom: '16px'
        }}>
          All Features Combined
        </h3>
        <TextArea
          label="AI Generated Summary"
          value={allFeaturesValue}
          onChange={(e) => setAllFeaturesValue(e.target.value)}
          isMagic
          size="small"
          maxLength={200}
          error={allFeaturesValue.length > 180 ? "Approaching character limit" : undefined}
          helperText={allFeaturesValue.length <= 180 ? "AI-generated content with character limit" : undefined}
          textAreaProps={{ placeholder: 'AI will generate content here...' }}
        />
      </section>

      <section>
        <h3 style={{
          fontSize: '18px',
          fontWeight: '700',
          fontFamily: 'var(--ld-semantic-font-family-sans)',
          color: 'var(--ld-semantic-color-text)',
          marginBottom: '16px'
        }}>
          Size Comparison
        </h3>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px' }}>
          <TextArea
            label="Large (Default)"
            value=""
            onChange={() => {}}
            helperText="128px height"
            textAreaProps={{ placeholder: 'Large size...' }}
          />
          <TextArea
            label="Small"
            value=""
            onChange={() => {}}
            size="small"
            helperText="100px height"
            textAreaProps={{ placeholder: 'Small size...' }}
          />
        </div>
      </section>
    </div>
  );
}
