import * as React from 'react';
import { MagicBox } from '@/components/ui/MagicBox';
import { Button } from '@/components/ui/Button';
import { ButtonGroup } from '@/components/ui/ButtonGroup';
import { StarFill } from '@/components/icons';

/**
 * Example component demonstrating MagicBox usage with Living Design 3.5
 * Shows how to wrap AI-generated content with the magic glow effect
 */
export const MagicBoxExample: React.FC = () => {
  const [isActive, setIsActive] = React.useState(false);
  const [loadingState, setLoadingState] = React.useState<'idle' | 'loading' | 'active'>('loading');

  return (
    <div style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '32px' }}>
      
      {/* Basic Usage */}
      <section>
        <h2 style={{ marginBottom: '16px', fontSize: '20px', fontWeight: 700 }}>
          Basic Usage
        </h2>
        <div style={{ marginBottom: '16px' }}>
          <ButtonGroup>
            <Button 
              variant={isActive ? 'primary' : 'secondary'}
              onClick={() => setIsActive(!isActive)}
            >
              {isActive ? 'Hide' : 'Show'} Magic Effect
            </Button>
          </ButtonGroup>
        </div>
        <MagicBox active={isActive} state="loading">
          <div
            style={{
              padding: '24px',
              backgroundColor: 'var(--ld-semantic-color-surface, #ffffff)',
              borderRadius: '16px',
              border: '1px solid var(--ld-semantic-color-border-subtle, #e0e0e0)',
            }}
          >
            <h3 style={{ marginBottom: '12px', fontSize: '18px', fontWeight: 600 }}>
              AI-Generated Content
            </h3>
            <p style={{ color: 'var(--ld-semantic-color-text-subtle, #666)', lineHeight: 1.6 }}>
              This content is being processed by AI. The magic glow effect indicates active AI operations.
            </p>
          </div>
        </MagicBox>
      </section>

      {/* Animation States */}
      <section>
        <h2 style={{ marginBottom: '16px', fontSize: '20px', fontWeight: 700 }}>
          Animation States
        </h2>
        <div style={{ marginBottom: '16px' }}>
          <ButtonGroup>
            <Button 
              variant={loadingState === 'idle' ? 'primary' : 'secondary'}
              onClick={() => setLoadingState('idle')}
            >
              Idle
            </Button>
            <Button 
              variant={loadingState === 'loading' ? 'primary' : 'secondary'}
              onClick={() => setLoadingState('loading')}
            >
              Loading
            </Button>
            <Button 
              variant={loadingState === 'active' ? 'primary' : 'secondary'}
              onClick={() => setLoadingState('active')}
            >
              Active
            </Button>
          </ButtonGroup>
        </div>
        <MagicBox active={true} state={loadingState}>
          <div
            style={{
              padding: '32px',
              backgroundColor: 'var(--ld-semantic-color-surface, #ffffff)',
              borderRadius: '16px',
              border: '1px solid var(--ld-semantic-color-border-subtle, #e0e0e0)',
              textAlign: 'center',
            }}
          >
            <div style={{ marginBottom: '12px' }}>
              <StarFill style={{ width: 32, height: 32, color: 'var(--ld-semantic-color-action-fill-primary, #0071DC)' }} />
            </div>
            <h3 style={{ marginBottom: '8px', fontSize: '18px', fontWeight: 600 }}>
              {loadingState === 'idle' && 'Idle - Static Glow'}
              {loadingState === 'loading' && 'Loading - Pulsing Animation'}
              {loadingState === 'active' && 'Active - Subtle Shimmer'}
            </h3>
            <p style={{ color: 'var(--ld-semantic-color-text-subtle, #666)' }}>
              {loadingState === 'idle' && 'Subtle static glow when AI is ready'}
              {loadingState === 'loading' && 'Pulsing effect while AI is processing'}
              {loadingState === 'active' && 'Gentle shimmer for active AI enhancement'}
            </p>
          </div>
        </MagicBox>
      </section>

      {/* Real-World Example - AI Recommendation */}
      <section>
        <h2 style={{ marginBottom: '16px', fontSize: '20px', fontWeight: 700 }}>
          Real-World Example: AI Recommendation
        </h2>
        <p style={{ marginBottom: '16px', color: '#666' }}>
          <strong>Note:</strong> The magic glow indicates this recommendation is being actively 
          generated by AI. Colors automatically adapt to the current theme.
        </p>
        <div 
          role="status" 
          aria-live="polite" 
          aria-label="AI is generating personalized recommendations"
          style={{ position: 'absolute', width: '1px', height: '1px', overflow: 'hidden' }}
        >
          AI is processing your recommendations
        </div>
        <MagicBox active={true} state="loading">
          <div
            style={{
              padding: '24px',
              backgroundColor: 'var(--ld-semantic-color-surface, #ffffff)',
              borderRadius: '16px',
              border: '1px solid var(--ld-semantic-color-border-subtle, #e0e0e0)',
            }}
          >
            <div style={{ display: 'flex', gap: '16px', alignItems: 'flex-start' }}>
              <div
                style={{
                  width: '80px',
                  height: '80px',
                  backgroundColor: 'var(--ld-semantic-color-fill-subtle, #f5f5f5)',
                  borderRadius: '8px',
                  flexShrink: 0,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <StarFill style={{ width: 32, height: 32, color: 'var(--ld-semantic-color-action-fill-primary, #0071DC)' }} />
              </div>
              <div style={{ flex: 1 }}>
                <h3 style={{ marginBottom: '8px', fontSize: '16px', fontWeight: 600 }}>
                  AI-Powered Recommendation
                </h3>
                <p style={{ color: 'var(--ld-semantic-color-text-subtle, #666)', fontSize: '14px', lineHeight: 1.6, marginBottom: '12px' }}>
                  Based on your browsing history and preferences, we recommend this product
                  tailored specifically for you.
                </p>
                <ButtonGroup>
                  <Button variant="primary" size="small">View Details</Button>
                  <Button variant="tertiary" size="small">Dismiss</Button>
                </ButtonGroup>
              </div>
            </div>
          </div>
        </MagicBox>
      </section>

      {/* Multiple Items */}
      <section>
        <h2 style={{ marginBottom: '16px', fontSize: '20px', fontWeight: 700 }}>
          Multiple AI Items
        </h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '16px' }}>
          <MagicBox active={true} state="loading">
            <div
              style={{
                padding: '20px',
                backgroundColor: '#ffffff',
                borderRadius: '16px',
                border: '1px solid #e0e0e0',
              }}
            >
              <h4 style={{ marginBottom: '8px', fontSize: '16px', fontWeight: 600 }}>
                Suggestion 1
              </h4>
              <p style={{ color: '#666', fontSize: '14px' }}>
                AI is analyzing your data to provide personalized insights.
              </p>
            </div>
          </MagicBox>
          
          <MagicBox active={true} state="loading">
            <div
              style={{
                padding: '20px',
                backgroundColor: '#ffffff',
                borderRadius: '16px',
                border: '1px solid #e0e0e0',
              }}
            >
              <h4 style={{ marginBottom: '8px', fontSize: '16px', fontWeight: 600 }}>
                Suggestion 2
              </h4>
              <p style={{ color: '#666', fontSize: '14px' }}>
                AI enhancement is active on this content.
              </p>
            </div>
          </MagicBox>
          
          <div
            style={{
              padding: '20px',
              backgroundColor: '#ffffff',
              borderRadius: '16px',
              border: '1px solid #e0e0e0',
            }}
          >
            <h4 style={{ marginBottom: '8px', fontSize: '16px', fontWeight: 600 }}>
              Regular Content
            </h4>
            <p style={{ color: '#666', fontSize: '14px' }}>
              This content has no AI processing (no magic effect).
            </p>
          </div>
        </div>
      </section>

      {/* Theme Responsiveness */}
      <section>
        <h2 style={{ marginBottom: '16px', fontSize: '20px', fontWeight: 700 }}>
          Theme Responsiveness
        </h2>
        <p style={{ marginBottom: '16px', color: '#666' }}>
          The Magic Box automatically adapts its colors based on the active theme:
        </p>
        <ul style={{ color: '#666', marginBottom: '16px', paddingLeft: '24px' }}>
          <li><strong>Default theme:</strong> Blue gradient (#0053E2 → #3D90EC → #79CDF6)</li>
          <li><strong>Developer theme:</strong> Blue-green gradient (#0053E2 → #A4FB6C → #79CDF6)</li>
        </ul>
        <MagicBox active={true} state="loading">
          <div
            style={{
              padding: '24px',
              backgroundColor: '#ffffff',
              borderRadius: '16px',
              border: '1px solid #e0e0e0',
              textAlign: 'center',
            }}
          >
            <p style={{ fontSize: '16px', fontWeight: 600 }}>
              Switch themes in the app to see the magic glow color change!
            </p>
          </div>
        </MagicBox>
      </section>

      {/* Accessibility Example */}
      <section>
        <h2 style={{ marginBottom: '16px', fontSize: '20px', fontWeight: 700 }}>
          Accessibility Best Practice
        </h2>
        <p style={{ marginBottom: '16px', color: '#666' }}>
          Always pair Magic Box with accessible status text for screen readers:
        </p>
        <div role="region" aria-label="AI processing status">
          <div 
            role="status" 
            aria-live="polite"
            style={{ 
              marginBottom: '12px',
              padding: '12px',
              backgroundColor: '#f5f5f5',
              borderRadius: '8px',
              fontSize: '14px',
            }}
          >
            <strong>Status:</strong> AI is currently processing your request...
          </div>
          <MagicBox active={true} state="loading">
            <div
              style={{
                padding: '24px',
                backgroundColor: '#ffffff',
                borderRadius: '16px',
                border: '1px solid #e0e0e0',
              }}
            >
              <h3 style={{ marginBottom: '12px', fontSize: '18px', fontWeight: 600 }}>
                Processing Request
              </h3>
              <p style={{ color: '#666' }}>
                Your AI-powered analysis is being generated. This may take a few moments.
              </p>
            </div>
          </MagicBox>
        </div>
      </section>

    </div>
  );
};
